// Generates the bash completion script for `photu completion`. Built from
// the same COMMANDS/COMMAND_META data the playground's autocomplete uses,
// so the two can't drift apart from each other - though both still have to
// be kept in sync with ops.ts's SPECS by hand (see completion-meta.ts).

import { COMMANDS } from "../core/ops.ts";
import { COMMAND_META } from "../core/completion-meta.ts";

// Commands outside COMMANDS (which is only the pipeline stages) that also
// appear as the first word of a photu invocation.
const UTILITY_COMMANDS = ["read", "info", "explain", "formats", "help", "completion"];
// Take a bare file/glob positional worth completing on disk.
const FILE_ARG_COMMANDS = new Set(["read", "info", "overlay", "write"]);

function words(list: readonly string[]): string {
  return list.join(" ");
}

function commandCase(cmd: string): string {
  const meta = COMMAND_META[cmd];
  const keyWords = Object.keys(meta.options).map((k) => `${k}=`);
  const wordList = words([...keyWords, ...meta.flags]);
  const fileFlag = FILE_ARG_COMMANDS.has(cmd) ? " -f" : "";
  return `    ${cmd}) COMPREPLY=( $(compgen${fileFlag} -W "${wordList}" -- "$cur") ) ;;`;
}

function enumCase(cmd: string, key: string, values: readonly string[]): string {
  return `      ${cmd}:${key}) COMPREPLY=( $(compgen -W "${words(values)}" -- "$val") ) ;;`;
}

export function generateBashCompletion(): string {
  const topLevel = words([...COMMANDS, ...UTILITY_COMMANDS]);

  const commandCases = COMMANDS.map(commandCase).join("\n");

  const enumCases = COMMANDS.flatMap((cmd) =>
    Object.entries(COMMAND_META[cmd].options)
      .filter(([, values]) => values !== null)
      .map(([key, values]) => enumCase(cmd, key, values as readonly string[])),
  ).join("\n");

  return `# bash completion for photu - generated by \`photu completion\`.
# Install by adding this to your shell profile (~/.bashrc or similar):
#   source <(photu completion)

# '=' is a word-break character in bash by default, which would otherwise
# split "fit=cover" into two completion words. photu's options are key=value,
# so drop '=' from the break set - a common technique (npm and docker's
# completions do the same) that only affects this shell's word splitting.
COMP_WORDBREAKS=\${COMP_WORDBREAKS//=}

_photu_completions() {
  local cur cmd key val
  cur="\${COMP_WORDS[COMP_CWORD]}"
  cmd="\${COMP_WORDS[1]}"

  if [[ \$COMP_CWORD -eq 1 ]]; then
    COMPREPLY=( $(compgen -W "${topLevel}" -- "\$cur") )
    return
  fi

  if [[ "\$cur" == *=* ]]; then
    key="\${cur%%=*}"
    val="\${cur#*=}"
    case "\$cmd:\$key" in
${enumCases}
      *) COMPREPLY=() ;;
    esac
    if [[ \${#COMPREPLY[@]} -gt 0 ]]; then
      COMPREPLY=( "\${COMPREPLY[@]/#/\$key=}" )
    fi
    return
  fi

  case "\$cmd" in
${commandCases}
    read|info) COMPREPLY=( $(compgen -f -- "\$cur") ) ;;
    explain|formats|help|completion) COMPREPLY=() ;;
    *) COMPREPLY=() ;;
  esac
}
complete -F _photu_completions photu
`;
}
